spring:
  profiles:
    active: zone1
  application:
    name: registry

server:
  port: 8081

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:${server.port}/eureka/